# Generated by Django 6.1.1 on 2026-09-12 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='público'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluído em'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='data do check-in')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='challenges.participation')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-date'],
                'unique_together': {('participation', 'date')},
            },
        ),
    ]
